<div>
    <form wire:submit.prevent="save" >
        <input type="file" id="myFile"/>
        <button type="button" id="submit" onclick="uploadChunks()">Submit</button>
    </form>

    <script> 
       
        function uploadChunks()
        {
            // File Details
            const file       = document.querySelector('#myFile').files[0];
            const chunkCount = Math.ceil(file.size/@js($chunkSize)); 
      
            // Sent along with next call
            @this.set('chunkCount', chunkCount, true);
            @this.set('fileName', file.name, true);
            
            // Upload chunks of file using uniqueId generated by server
            livewireUploadChunk( file, 0 );
        }
        
        function livewireUploadChunk( file, start ) 
        {
            // Get chunk from start
            const chunkEnd  = Math.min( start + @js($chunkSize), file.size );
            const chunk     = file.slice( start, chunkEnd ); 

            // Upload chunk with Livewire
            @this.upload('fileChunk', chunk);

            // Move to the next chunk
            start = chunkEnd;
            if( start < file.size ){
                livewireUploadChunk( file, start );
            }
        }

    </script>
</div>
